name: Create PR from design to main

# design ë¸Œëœì¹˜ì˜ tokens.json íŒŒì¼ì— ëŒ€í•œ push ê°ì§€
on:
  push:
    branches:
      - feat/design
    paths:
      - "src/assets/tokens.json"

permissions:
  pull-requests: write
  packages: read
  contents: write

jobs:
  createPullRequest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run:
          yarn install
          #ë””ìì¸ í† í°ì—ì„œ ê³„ì‚° ì²˜ë¦¬í•´ì£¼ëŠ” 1ì°¨ ê°€ê³µ
      - name: Run Token Transformer
        run: |
          yarn run token-transformer
          git config --global user.name "Sleepingoff"   
          git config --global user.email "justjh30@gmail.com"
          git add .
          git commit -m "í”¼ê·¸ë§ˆ ë””ìì¸ í† í° íŒŒì¼ ë³€í™˜"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Create Pull Request
        run: gh pr create -B develop -H feat/design --title 'ğŸ’„ ë””ìì¸ í† í° ì—…ë°ì´íŠ¸' --body 'ë””ìì¸ í† í°ì´ ì—…ë°ì´íŠ¸ í›„ ë³€í™˜ì‘ì—…ì„ ìˆ˜í–‰í–ˆìŠµë‹ˆë‹¤.'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
